### ISSUE TITLE
Mobile Display mode does not show or blur background

### ISSUE THREAD

**Issue by hackmonker** [CTalvio/Monochromic#18]
Currently Running Version: 10.7.0 (latest RC3 I believe) and android app v2.2.3
OS - Debian

Issue - The Homepage and library pages work as expected in both desktop and mobile. However in the details page only desktop works as expected. In mobile, the background is not loaded and neither does it blur. Don't know if its something on my end or the css.

CSS Used - 

@import url('https://ctalvio.github.io/Monochromic/default_style.css');
@import url('https://ctalvio.github.io/Monochromic/improve-performance_style.css');
@import url('https://ctalvio.github.io/Monochromic/alternate-itempage_style.css');

Screenshots - 

https://imgur.com/a/Tv9pTOG - Using the browser in PC
https://imgur.com/nW0PNEx - Using android app

**Comment by CTalvio** [comment]
This is not a problem with the theme. 10.7.0 no longer _has_ backdrops _to_ display on the mobile item page.

Actually, they were already gone in 10.6.4, the only reason the chromic themes had them, was due to a hacky way to bring them back. (The backdrops were still displayed on the mobile page, just not as backdrops, the theme changed them back). That method no longer works, as the backdrop related html code is now gone entirely from the mobile UI item page.

If backdrops are brought back on mobile, (which they likely will be), I will once again support them in the theme.

**Comment by CTalvio** [comment]
I have created an add-on for 10.7.0, that sacrifices the cover image to turn it into a backdrop on mobile.

**Comment by hackmonker** [comment]
Wow thanks a lot. Also I know this might be rude but you are free to reject. Really love the work you have done. Are you on discord or matrix or something. Would love to talk about a few css changes. It's fine if you reject. Just did not want to clog the github  issue with some queries. Thanks again 😊

**Comment by CTalvio** [comment]
You can find me on reddit as u/EdgeMentality

I'm on discord too, but that account is private. If you have general suggestions, you are free to create an issue here to present them.
