### ISSUE TITLE
Doesn't seem to work with 10.7.0

### ISSUE THREAD

**Issue by the1trujok3r** [CTalvio/Monochromic#19]
With RC3 released I was looking at the CSS changes and it seems to have broken most import CSS themes.

Any chance to look into making one that's 10.7.0 compatible

**Comment by CTalvio** [comment]
I am currently on RC3, the theme gets applied fine, and I have already made various updates due to changes in the UI.

Did the themes work for you in 10.6.4? Are you sure the version change is the reason for CSS overrides not working for you?

**Comment by the1trujok3r** [comment]
It did work properly in 10.6.4 and the only thing done was to use the installer for windows x64 for the 10.7.0rc3

None of theme is being applied outside of the font.

I've tested in FireFox and in Chrome both latest versions.

**Comment by CTalvio** [comment]
Ok. Weird. There is absolutely nothing new in the 10.7.0 update that should affect themes, aside from UI changes that may break something (which I have already fixed).

What does your Custom CSS field currently contain?

What happens if you paste the entire theme code in (copy paste the content of the css files, instead of using @import)?

Are you using a reverse proxy?

**Comment by n8llcaster** [comment]
Confirmed. It doesn't work with 10.7.0 RC4.

What does your Custom CSS field currently contain? Just basic css file without additional mods from you.
Are you using a reverse proxy? No, nothing just fresh server with single css file.
What happens if you paste the entire theme code in (copy paste the content of the css files, instead of using @import)? Same as css link

Edit: Problem also affect Kaleidochromic

**Comment by CTalvio** [comment]
It's most certainly NOT confirmed, as the theme works for me.

The reason I asked what is in your CSS field is because I wanted to know the exact text content for troubleshooting purposes. You gave me a vague verbal description.

If even writing the whole theme as-is does not apply it, then something is very wrong with your instance, and I cannot help without you providing significantly more, and exact, information.

I do not have this problem, I am literally running the release candidates myself in order to update the themes for them, and they WORK.

You need to tell me the precise circumstances in which the problem occurs.

**Comment by CTalvio** [comment]
Have you waited for/cleared your browser cache to reload it?

**Comment by n8llcaster** [comment]
Good news. Stable 10.7.0 fixed issue.

I did a clean install (and manually deleted leftovers) newly released stable version and everything seems to be working after server restart.
