### ISSUE TITLE
Theme is not being applied

### ISSUE THREAD

**Issue by rernars** [CTalvio/Monochromic#21]
I am using jellyfin 10.7.6 , It seems that only some of the css works . 
![image](https://user-images.githubusercontent.com/59098807/124352240-f3513780-dc07-11eb-9a05-e3c34dbfab2e.png)
![image](https://user-images.githubusercontent.com/59098807/124352442-d23d1680-dc08-11eb-99ca-165624a40ccd.png)

These are the css rules i added 
![image](https://user-images.githubusercontent.com/59098807/124352283-314e5b80-dc08-11eb-9acc-0cc464dd9d14.png)

Since some of the css's work (like the login page) i dont think its NGINX's error. What do you think could be the problem?
EDIT: Just learned that i need to enable backdrops from the settings

**Comment by CTalvio** [comment]
Yeah.

In addition, not sure what color picker you used to get an RGB value with decimals, but RGB is supposed to be whole numbers of 0-255. 

Also, you have entered an RGBA value instead of a RGB value, along with the parenthesis and RGBA text. This is a VARIABLE and those parts are not to be included as they are already there in the places where the theme uses the color value. It just grabs the numbers from the variable, with your value, it ALSO grabs extra parenthesis and text.

The accent variable is supposed to be formatted like this:
`:root {--accent: R, G, B;}`

To set the accent to red, for example:
`:root {--accent: 255, 0, 0;}`

**Comment by CTalvio** [comment]
Actually, you are using the old accent color add-on. It's supposed to be:
`@import url('https://ctalvio.github.io/Monochromic/customcolor-advanced_style.css');`

Not: 
`@import url('https://ctalvio.github.io/Monochromic/customcolor_style.css');`

**Comment by rernars** [comment]
I use Skin Manager to change between themes, they probably didnt change it to the newer one. I'll write to them about this, thx for your reply.

**Comment by erennnars** [comment]
Oh and btw is there a way to make the navbar thinner like this from css/settings? Because mine is taking so much space and i think the example images of the theme was like the one in the picture.

![image](https://user-images.githubusercontent.com/59098807/124358171-bb59ec80-dc27-11eb-8fc6-e01dfed41427.png)

**Comment by rernars** [comment]
And I just made a css (changed jellyflix's Logo.css) that adds the Logo of the movie/show instead of the movie title. I am not the best at css but I thought you could improve it so heres the link + pictures . Hope You like it

Raw: [https://erennnars.github.io/Logo.css](https://erennnars.github.io/Logo.css)
[https://github.com/erennnars/erennnars.github.io/blob/main/Logo.css](https://github.com/erennnars/erennnars.github.io/blob/main/Logo.css
)
![image](https://user-images.githubusercontent.com/59098807/124432542-6975ab80-dd7a-11eb-8d78-28dbf5a14e52.png)

![image](https://user-images.githubusercontent.com/59098807/124433205-28ca6200-dd7b-11eb-8c2d-30f02f2ff610.png)
